exclude: 'docs|node_modules|.git|.tox|deploy'
default_stages: [commit]
fail_fast: true
default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
      - id: check-ast
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        exclude: 'deploy/.*'
      - id: check-json
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: forbid-crlf
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ "--line-length=120" ]
        exclude: ^apps/|migrations
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^apps/|migrations
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        entry: bash -c 'mypy "$@" || true' --
        args: [ "--no-strict-optional", "--ignore-missing-imports" ]
        exclude: ^apps/|migrations
