version: '3.1'

services:
  postgres:
    image: postgres:13.4
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    logging:
      driver: none


  app:
    build: .
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
